### ISSUE TITLE
Disk image created on disk mounted from NFS share can't be erased

### ISSUE THREAD

**Issue by ssbaksa** [Bandic007/WebVirtCloud-B7#6] opened 2018-09-19 14:12 UTC
![image](https://user-images.githubusercontent.com/19958704/45758813-cb46e400-bc26-11e8-808f-4dbce7bcc570.png)

**Comment by ssbaksa** [comment] 2018-09-19 14:56
It is created by WVC but can't be erased by it. It is the sam NFS strorage
used by 7 other Computes. Localy created image was deleted without problem.

**Comment by ssbaksa** [comment] 2018-09-19 18:00
For some reasons uknown to me Compute node where latest version WVC resides
created image vith "funny" ownership:

-rw-r--r-- 1 messagebus crontab     10739318784 Sep 19 16:06 test123.img

Another example is created some days ago with ratspens version of WVC on
the same NFS share

-rw------- 1 root       root        26847870976 Aug 29 08:25 Test.img

I must investigate into that.

P.S. If you wish some of communication can be done directly over the e-mail
not to clutter GIT and error page if not necessary.
ssbaksa@gmail.com

Br

Sasa

**Comment by Bandic007** [comment] 2018-09-19 18:11
can you test if it is happening with every created image or was some kind of anomally?

**Comment by ssbaksa** [comment] 2018-09-19 18:15
I will do that first thing in the morning.

**Comment by ssbaksa** [comment] 2018-09-20 05:56
Hi
It is tied to latest version (2.5.1) I have used the same server as Compute node but 2 different servers as WVC conetcting to that copute node (tcp connection to libvirt)

Findings and logs are in 3 separate files

[NFS and LOCAL storage creation v102.txt](https://github.com/Bandic007/WebVirtCloud-B7/files/2399861/NFS.and.LOCAL.storage.creation.v102.txt)
[NFS storage creation.txt](https://github.com/Bandic007/WebVirtCloud-B7/files/2399862/NFS.storage.creation.txt)
[LOCAL storage creation.txt](https://github.com/Bandic007/WebVirtCloud-B7/files/2399863/LOCAL.storage.creation.txt)

**Comment by ssbaksa** [comment] 2018-09-20 05:57
Cloased by mistake, Sorry.

**Comment by Bandic007** [comment] 2018-09-20 08:19
@ssbaksa - can you try with webvirtcloud with latest changes from @catborise repo? It is almost the same just some cosmetic changes and minor functionalities that are not there. I want to cinfirm the problem is in some of my latest changes, not global.

**Comment by ssbaksa** [comment] 2018-09-20 08:32
Ok, i will do that during today but on completely different server (which
is the same hardware and Ubuntu version as all nodes where I do testing) so
we can compare results.

Br

Saša

**Comment by ssbaksa** [comment] 2018-09-20 09:50
Same problem

-rw-r--r-- 1 messagebus crontab 10739318784 Sep 20 11:45 test2c.img

TypeError at /compute/1/storage/local/

success() takes at least 2 arguments (1 given)

Request Method: POST
Request URL: http://172.17.252.168:80/compute/1/storage/local/
Django Version: 1.11.14
Exception Type: TypeError
Exception Value:

success() takes at least 2 arguments (1 given)

Exception Location: /srv/webvirtcloud/storages/views.py in storage, line 158
Python Executable: /srv/webvirtcloud/venv/bin/python2
Python Version: 2.7.12
Python Path:

['/srv/webvirtcloud',
 '/srv/webvirtcloud/venv/bin',
 '/srv/webvirtcloud/venv/lib/python2.7',
 '/srv/webvirtcloud/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-tk',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-old',
 '/srv/webvirtcloud/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/srv/webvirtcloud/venv/local/lib/python2.7/site-packages']

Server time: Thu, 20 Sep 2018 09:45:46 +0000

**Comment by Bandic007** [comment] 2018-09-20 09:52
ok so I think it will be best to close the issue here and open one in the retspen original repo as @catborise is contributor there. They will fix it then I am sure.

**Comment by ssbaksa** [comment] 2018-09-20 09:54
Ok, close it.

**Closed** 2018-09-20 09:58 UTC
